# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @return a random matrix of nrow \code{N} and ncol 2
#' @examples
#' \dontrun{
#' x<-gibbs_C(5000)
#' }
#' @export

##
gibbs_C <- function(N) {
    .Call('_StatComp21095_gibbs_C', PACKAGE = 'StatComp21095', N)
}

